services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: KiranM
      WORDPRESS_DB_PASSWORD: KiranM1988
      WORDPRESS_DB_NAME: KiranDB
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: KiranDB
      MYSQL_USER: KiranM
      MYSQL_PASSWORD: KiranM1988
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
